# CareLink Android release build daemon fix (Windows PowerShell)
# Run from flutter_app:
# powershell -ExecutionPolicy Bypass -File .\tool\fix_android_gradle.ps1

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$androidDir = Join-Path $projectRoot 'android'
$gradleWrapper = Join-Path $androidDir 'gradlew.bat'

if (-not (Test-Path $gradleWrapper)) {
  throw "android\gradlew.bat topilmadi. Avval: flutter create . --platforms=android --org com.modder --project-name carelink"
}

$safeProperties = @"
# CareLink safe Gradle settings - generated by tool/fix_android_gradle.ps1
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.internal.instrumentation.agent=false
android.useAndroidX=true
android.enableJetifier=true
"@

function Backup-And-Write([string]$path) {
  $existing = @()
  if (Test-Path $path) {
    Copy-Item $path "$path.bak" -Force
    $existing = Get-Content $path | Where-Object {
      $_ -notmatch '^(org\.gradle\.(jvmargs|daemon|parallel|workers\.max|internal\.instrumentation\.agent)|android\.(useAndroidX|enableJetifier))='
    }
  }
  $existing += $safeProperties.Trim().Split("`n")
  Set-Content -Path $path -Value $existing -Encoding UTF8
  Write-Host "Updated: $path" -ForegroundColor Green
}

# Project settings Gradle build uchun asosiy manba.
Backup-And-Write (Join-Path $androidDir 'gradle.properties')

# Android permissionlar: FCM push va SOS location olish uchun.
$manifestPath = Join-Path $androidDir 'app\src\main\AndroidManifest.xml'
if (Test-Path $manifestPath) {
  $manifest = Get-Content -Raw $manifestPath
  $neededPermissions = @(
    'android.permission.INTERNET',
    'android.permission.POST_NOTIFICATIONS',
    'android.permission.ACCESS_FINE_LOCATION',
    'android.permission.ACCESS_COARSE_LOCATION'
  )
  $missing = @()
  foreach ($permission in $neededPermissions) {
    if ($manifest -notmatch [regex]::Escape("android:name=\"$permission\"")) {
      $missing += "<uses-permission android:name=\"$permission\" />"
    }
  }
  if ($missing.Count -gt 0) {
    Copy-Item $manifestPath "$manifestPath.bak" -Force
    $applicationIndex = $manifest.IndexOf('<application')
    if ($applicationIndex -ge 0) {
      $permissionBlock = "    " + ($missing -join "`r`n    ") + "`r`n    "
      $manifest = $manifest.Insert($applicationIndex, $permissionBlock)
      Set-Content -Path $manifestPath -Value $manifest -Encoding UTF8
      Write-Host "Added Android FCM + location permissions to manifest." -ForegroundColor Green
    }
  }
}

# User global properties eski -Xmx8G qiymatini qayta yuklamasligi uchun tozalanadi.
$userGradleDir = Join-Path $env:USERPROFILE '.gradle'
$userProps = Join-Path $userGradleDir 'gradle.properties'
if (Test-Path $userProps) {
  Copy-Item $userProps "$userProps.bak" -Force
  $lines = Get-Content $userProps | Where-Object {
    $_ -notmatch '^(org\.gradle\.(jvmargs|daemon|parallel|workers\.max|internal\.instrumentation\.agent)|android\.(useAndroidX|enableJetifier))='
  }
  $lines += $safeProperties.Trim().Split("`n")
  Set-Content -Path $userProps -Value $lines -Encoding UTF8
  Write-Host "Updated global: $userProps" -ForegroundColor Yellow
}

Push-Location $androidDir
try {
  & .\gradlew.bat --stop
  if (Test-Path '.gradle') { Remove-Item -Recurse -Force '.gradle' }
} finally {
  Pop-Location
}

Write-Host "Done. Now run:" -ForegroundColor Cyan
Write-Host "  cd $projectRoot"
Write-Host "  flutter clean"
Write-Host "  flutter pub get"
Write-Host "  flutter build apk --release"
